[versions]
androidx-lifecycle = "2.8.3"
composeMultiplatform = "1.7.0"
kotlin = "2.0.21"

[libraries]
orgJetbrainsAndroidxLifecycle-lifecycleViewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
orgJetbrainsAndroidxLifecycle-lifecycleRuntimeCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

[plugins]
orgJetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
orgJetbrainsKotlinPluginCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
orgJetbrainsKotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ioGitlabArturboschDetekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.7" }
comDiffplugSpotless = { id = "com.diffplug.spotless", version = "6.25.0" }
